# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6f24515d7f4e3bf2899c783d12101f37a9ce0a3e7fb3d75338dfaf4175d86cb03b61e19705424685d88a0a08156a79fbcc1e2e8c9affa101b2313912a5396ca

test:
  secret_key_base: 42919f9f155c99e39770609ac3db3770968b6b4243cd1ff4064eeba1cc602fd3b17114f4b4398d991df6574b239930df5121b0346eccd158190419bbcd40c877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
